name: 'Agent Audit'
description: 'Security scanner for AI agents and MCP configurations. Detects vulnerabilities based on OWASP Agentic Top 10.'
author: 'HeadyZhang'
branding:
  icon: 'shield'
  color: 'purple'

inputs:
  path:
    description: 'Path to scan (default: current directory)'
    required: false
    default: '.'
  format:
    description: 'Output format: terminal, json, sarif, markdown'
    required: false
    default: 'sarif'
  output:
    description: 'Output file path (required for sarif format)'
    required: false
    default: 'agent-audit-results.sarif'
  severity:
    description: 'Minimum severity to report: info, low, medium, high, critical'
    required: false
    default: 'low'
  fail-on:
    description: 'Exit with error if findings at this severity: low, medium, high, critical'
    required: false
    default: 'high'
  baseline:
    description: 'Path to baseline file for incremental scanning'
    required: false
  upload-sarif:
    description: 'Upload SARIF to GitHub Security tab (true/false)'
    required: false
    default: 'true'

outputs:
  total_findings:
    description: 'Total number of security findings detected'
    value: ${{ steps.scan.outputs.total_findings }}
  critical_count:
    description: 'Number of CRITICAL severity findings (security-severity >= 9.0)'
    value: ${{ steps.scan.outputs.critical_count }}
  high_count:
    description: 'Number of HIGH severity findings (security-severity >= 7.0, < 9.0)'
    value: ${{ steps.scan.outputs.high_count }}
  medium_count:
    description: 'Number of MEDIUM severity findings (security-severity >= 4.0, < 7.0)'
    value: ${{ steps.scan.outputs.medium_count }}
  low_count:
    description: 'Number of LOW severity findings (security-severity < 4.0)'
    value: ${{ steps.scan.outputs.low_count }}
  scan_status:
    description: 'Scan status: success (exit code 0) or failure (findings exceed fail-on threshold)'
    value: ${{ steps.scan.outputs.scan_status }}
  sarif_file:
    description: 'Path to the generated SARIF file (if format=sarif)'
    value: ${{ steps.scan.outputs.sarif_file }}
  findings-count:
    description: 'Total number of findings (deprecated: use total_findings)'
    value: ${{ steps.scan.outputs.total_findings }}
  exit-code:
    description: 'Exit code from scan (deprecated: use scan_status)'
    value: ${{ steps.scan.outputs.exit_code }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install agent-audit
      shell: bash
      run: |
        pip install agent-audit

    - name: Run agent-audit scan
      id: scan
      shell: bash
      run: |
        set +e  # Don't exit on error

        ARGS="${{ inputs.path }}"
        ARGS="$ARGS --format ${{ inputs.format }}"

        OUTPUT_FILE="${{ inputs.output }}"
        if [ "${{ inputs.format }}" == "sarif" ] || [ -n "$OUTPUT_FILE" ]; then
          ARGS="$ARGS --output $OUTPUT_FILE"
        fi

        ARGS="$ARGS --severity ${{ inputs.severity }}"
        ARGS="$ARGS --fail-on ${{ inputs.fail-on }}"

        if [ -n "${{ inputs.baseline }}" ]; then
          ARGS="$ARGS --baseline ${{ inputs.baseline }}"
        fi

        agent-audit scan $ARGS
        EXIT_CODE=$?

        # Set exit code and scan status
        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
        if [ $EXIT_CODE -eq 0 ]; then
          echo "scan_status=success" >> $GITHUB_OUTPUT
        else
          echo "scan_status=failure" >> $GITHUB_OUTPUT
        fi

        # Parse SARIF file to extract structured counts
        if [ -f "$OUTPUT_FILE" ]; then
          echo "sarif_file=$OUTPUT_FILE" >> $GITHUB_OUTPUT

          # Total findings count
          TOTAL=$(jq '.runs[0].results | length' "$OUTPUT_FILE" 2>/dev/null || echo "0")
          echo "total_findings=$TOTAL" >> $GITHUB_OUTPUT

          # Count findings by severity using rule security-severity scores
          # CVSS-aligned thresholds: Critical>=9.0, High>=7.0, Medium>=4.0, Low<4.0
          COUNTS=$(jq -r '
            # Build a map of ruleId -> security-severity score
            (
              [.runs[0].tool.driver.rules[]? |
               {key: .id, value: ((.properties."security-severity" // "0") | tonumber)}
              ] | from_entries
            ) as $sev_map |

            # Count results by severity category
            reduce (.runs[0].results[]?) as $r (
              {critical: 0, high: 0, medium: 0, low: 0};
              ($sev_map[$r.ruleId] // 0) as $score |
              if $score >= 9 then .critical += 1
              elif $score >= 7 then .high += 1
              elif $score >= 4 then .medium += 1
              else .low += 1
              end
            ) |
            "critical_count=\(.critical)\nhigh_count=\(.high)\nmedium_count=\(.medium)\nlow_count=\(.low)"
          ' "$OUTPUT_FILE" 2>/dev/null)

          if [ -n "$COUNTS" ]; then
            echo "$COUNTS" >> $GITHUB_OUTPUT
          else
            # Fallback if jq parsing fails
            echo "critical_count=0" >> $GITHUB_OUTPUT
            echo "high_count=0" >> $GITHUB_OUTPUT
            echo "medium_count=0" >> $GITHUB_OUTPUT
            echo "low_count=0" >> $GITHUB_OUTPUT
          fi
        else
          # No SARIF file - set all counts to 0
          echo "sarif_file=" >> $GITHUB_OUTPUT
          echo "total_findings=0" >> $GITHUB_OUTPUT
          echo "critical_count=0" >> $GITHUB_OUTPUT
          echo "high_count=0" >> $GITHUB_OUTPUT
          echo "medium_count=0" >> $GITHUB_OUTPUT
          echo "low_count=0" >> $GITHUB_OUTPUT
        fi

        exit $EXIT_CODE

    - name: Upload SARIF to GitHub Security
      if: inputs.upload-sarif == 'true' && inputs.format == 'sarif'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.output }}
